name: .NET

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.fs'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Test
      run: dotnet test ./test --nologo --logger "console;verbosity=normal"