name: .NET

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.fs'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      uses: ./.github/workflows/setup.yml
    - name: Format
      run: npm run format:check
    - name: Test
      run: npm run test