name: .NET

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.fs'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 22
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Install NPM dependencies
      run: npm i
    - name: Install .NET tools
      run: dotnet tool restore
    - name: Format
      run: npm run format:check
    - name: Test
      run: npm run test